# Generated by Django 4.1.3 on 2022-12-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='managerid',
            field=models.IntegerField(),
        ),
    ]
