# Generated by Django 4.1.3 on 2022-12-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0002_alter_employee_managerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Emailid',
            new_name='emailid',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Mobileno',
            new_name='mobileno',
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(),
        ),
    ]
