# Generated by Django 4.1.3 on 2022-12-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0003_rename_emailid_employee_emailid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photograph',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
