# Generated by Django 4.1.3 on 2022-12-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0008_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alternateno',
            field=models.CharField(default='', max_length=12),
        ),
    ]
