# Generated by Django 4.1.3 on 2022-12-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0009_customer_alternateno'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(default='', max_length=45),
        ),
    ]
