# Generated by Django 4.1.3 on 2023-01-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0010_employee_password_manager_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileno', models.CharField(default='', max_length=45)),
                ('password', models.CharField(default='', max_length=45)),
                ('adminname', models.CharField(default='', max_length=45)),
            ],
        ),
    ]
