# Generated by Django 4.1.3 on 2023-01-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0011_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.IntegerField()),
                ('customerid', models.IntegerField()),
                ('customername', models.CharField(default='', max_length=45)),
                ('callerid', models.IntegerField()),
                ('status', models.CharField(default='', max_length=45)),
                ('callername', models.CharField(default='', max_length=45)),
                ('currentdate', models.DateField()),
                ('phonestatus', models.CharField(default='', max_length=45)),
                ('conversation', models.CharField(default='', max_length=200)),
                ('leadstatus', models.CharField(default='', max_length=45)),
            ],
        ),
    ]
