# Generated by Django 4.1.3 on 2023-01-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0012_calldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetail',
            name='mobileno',
            field=models.CharField(default='', max_length=12),
        ),
    ]
