# Generated by Django 4.1.3 on 2023-01-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0013_calldetail_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='callerid',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='customerid',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='transactionid',
            field=models.CharField(default='', max_length=45),
        ),
    ]
