# Generated by Django 4.1.3 on 2023-01-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0014_alter_calldetail_callerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calldetail',
            name='transactionid',
        ),
    ]
